Обработке ошибок в Go нашлось особое место. Во многих других языках ошибки обрабатываются с помощью механизма исключений (exceptions). Если в ходе выполнения функции происходит ошибка, выбрасывается специальное событие (исключение), которое будет либо сразу обработано в месте вызова функции, либо проброшено вверх по стеку, пока его кто-нибудь не поймает. Ловить это событие нужно с помощью конструкции `try — catch`, также известной как обработчик исключений:

У этого подхода есть недостаток: выброс исключения происходит неявно для кода, вызывающего функцию, поэтому программист должен запоминать, какая функция может выбросить исключение. Также существуют uncatchable-исключения — например, относящиеся к выходу программы за пределы доступной ей памяти.

В Go применяется другой подход, который вносит больше ясности и наглядности в процесс обработки ошибок. Функции в Go могут возвращать больше одного значения, и этим активно пользуются разработчики, указывая в качестве последнего возвращаемого значения интерфейс `error`:

```go
func foo() (int, error) { 
    // в теле функции может быть ошибка
}

result, err = foo()
if err != nil {
    // handle error
} 
```

Тип `error` в Go — встроенный, то есть для обращения к нему не нужно импортировать какой-либо пакет. Наличие отдельного типа позволяет одинаково обрабатывать ошибки, независимо от того, с какой функцией вы работаете — стандартной или сторонней библиотеки. Вы всегда работаете с одним и тем же интерфейсом `error`, поэтому можете сравнить две ошибки или применить к ним функции интроспекции ошибок из библиотеки `errors`.


[[Основы Go]]