Допустим, есть функция, которая извлекает значение по ключу из карты и возвращает ошибку, если ключ не найден:

```go
var errNotFound error = errors.New("not found")

func getValue(m map[string]string, key string) (string, error) {
    val, ok := m[key]
    if !ok {
        return "", errNotFound
    }
    return val, nil
}
```

И есть структура `languages` с информацией о языках. Она возвращает описание языка по названию:

```go
type languages map[string]string

func (l languages) describe(lang string) (string, error) {
    descr, err := getValue(l, lang)
    if err != nil {
        return "", err
    }
    return descr, nil
}
```

```go
var langs languages = languages{
    "go":     "is awesome",
    "python": "is everywhere",
    "php":    "just is",
}

func main() {
    descr, err := langs.describe("java")
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println(descr)
}
```

Внутри у `languages` карта, а метод `languages.describe()` использует `getValue()`, чтобы получить информацию о языке по названию. Получив ошибку, метод транслирует ее клиенту. В примере для `"java"` напечатается такой результат:

```no-highlight
not found
```

Формально все верно. Но `errNotFound` — низкоуровневая ошибка общего назначения. Она ничего не говорит о проблеме с поиском языка. Клиент хотел бы больше информации.

Можно создать новую ошибку в `describe()` с помощью `fmt.Errorf()`:

```go
func (l languages) describe(lang string) (string, error) {
    descr, err := getValue(l, lang)
    if err != nil {
        return "", fmt.Errorf("error describing %s: unknown language", lang)
    }
    return descr, nil
}
```

```no-highlight
error describing java: unknown language
```

Но создав новую ошибку, мы потеряли информацию о первоначальной `errNotFound`. Вдруг клиенту она важна?

Можно _обернуть_ (wrap) исходную ошибку в новую с помощью `fmt.Errorf()`  и спецификатора `%w`:

```go
func (l languages) describe(lang string) (string, error) {
    descr, err := getValue(l, lang)
    if err != nil {
        return "", fmt.Errorf("error describing %s: %w", lang, err)
    }
    return descr, nil
}
```

Теперь метод возвращает ошибку-матрешку: снаружи у нее информативная `error describing...`, а внутри исходная `errNotFound`. В сложных программах таких «обертываний» может быть много, пока ошибка поднимается от самых нижних слоев кода к уровню API или UI.

[[Recover]] [[Panic]] [[Собственный тип ошибки]] [[Ошибки]]